### ISSUE TITLE
Examples don't work with current PIP crossbar

### ISSUE THREAD

**Issue by cupofnestor** [tavendo/AutobahnJS#109]
I'm not sure if this is an issue for AutobahnJS, AutobahnPython, or perhaps crossbar.

Since pip installed crossbar started installing Autobahn>0.8.10, examples and code based on examples/tutorials don't work.   I'm on OSX using Python 2.7.8 installed via homebrew.  The default crossbar version installed by PIP looks like this -
```
    Crossbar.io software versions:
    Crossbar.io     : 0.9.8-3
    Autobahn        : 0.9.1
    Twisted         : 14.0.2-KQueueReactor
    Python          : 2.7.8
    UTF8 Validator  : autobahn
    XOR Masker      : autobahn
```
When running example code, connection does not open.
I've tested with my own code as well as the pubsub examples:
https://github.com/tavendo/AutobahnPython/tree/master/examples/twisted/wamp/basic/pubsub/basic

The only way I've gotten examples working is to rollback autobahn/crossbar:
```
Crossbar.io     : 0.9.6
Autobahn        : 0.8.10
Twisted         : 14.0.0-KQueueReactor
Python          : 2.7.8
UTF8 Validator  : autobahn
XOR Masker      : autobahn
```

**Comment by oberstet** [comment]
the AutobahnPython repo currently contains quite some outdated examples. these work and are (hopefully all) current: https://github.com/crossbario/crossbarexamples
