### ISSUE TITLE
AutobahnJS / NodeJS Session.publish eligible/exclude parameter broken

### ISSUE THREAD

**Issue by fr34kyn01535** [tavendo/AutobahnJS#115]
Whenever i try to execute
```javascript
 session.publish('com.test.procedure', [], {}, { eligible:details.caller});
```
with any eligible session id that really exists, the nodejs worker crashes. Sadly i dont get an error message. The same problem occurs when using exclude instead of eligible!

Full reproduction:

NodeJS
```javascript
connection.onopen = function (session) {
	session.register('com.test.procedure',function(args,kwargs,details) {
		console.log("Procedure called, triggering the event now");
		connection.session.publish('com.test.event', [], {}, { eligible:[details.caller]});
	}
}        
```

Javascript Client
```javascript
connection.onopen = function (session) {
	session.subscribe('com.test.event', function(){console.log("Event triggered")});
	session.call('com.test.procedure', [],{},{disclose_me: true});
}
```

Output in crossbar console:
```javascript
connection.onclose triggered: lost { reason: null,
message: null,
retry_delay: 1.6914366128660279,
retry_count: 1,
will_retry: true }
```

Crossbar.io     : 0.9.10
Autobahn        : 0.9.3
UTF8 Validator  : autobahn
XOR Masker      : autobahn
Twisted         : 14.0.2-EPollReactor
Python          : 2.7.6-CPython
OS              : Linux-3.13.0-32-generic-x86_64-with-Ubuntu-14.04-trusty
Machine         : x86_64

**Comment by oberstet** [comment]
eligible and exclude are **lists**
