### ISSUE TITLE
onabort handler

### ISSUE THREAD

**Issue by ysobolev** [tavendo/AutobahnJS#118]
Please add an onabort() handler. The default action should be to call onleave, however the user should be able to override this. This is to separate ABORT messages from more general failures which cause a session to end. Yes, there is a URI to help distinguish them, but it is helpful to know that there was an explicit ABORT (which may, in theory, have multiple different URIs associated with it).

**Comment by oberstet** [comment]
`ABORT` only appears during WAMP handshake and shouldn't be exposed to the user
