### ISSUE TITLE
"Uncaught ReferenceError: ab is not defined" error on some websites

### ISSUE THREAD

**Issue by nhouse** [tavendo/AutobahnJS#121]
I'm developing a bookmarklet that creates a popup on external sites and allows users to enter comments. I would like to use AutobahnJS as the client-side of a WAMP server to allow new comments to be pushed to clients. 

AutobahnJS works on most websites I've tried including it on, but it does not work on some sites.

Here's example code to include it on a site:

        var script = document.createElement("script");
        script.type = "text/javascript";
        script.src = "http://autobahn.s3.amazonaws.com/js/autobahn.min.js ";
        script.charset="utf-8";
        document.body.appendChild(script);

If you try executing that on Amazon, as an example, it works without a problem.

However, if you try running it on http://www.backcountry.com, the following error is outputted to the console:

    Uncaught ReferenceError: ab is not defined                       autobahn.min.js:formatted:1197

Why is this error thrown on some sites?

**Comment by oberstet** [comment]
It's not working because you are hot-linking - please host the files on your own servers. http://autobahn.ws/js/gettingstarted.html#browsers

We have had sites with millions of hits per day .. and that does add up.

**Comment by nhouse** [comment]
Hi Tobias,

Wow, thanks for the quick response.

I only used the direct link for the example above. Here is another example with the file hosted on my server:

    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "http://www.pricewombat.com/assets/libraries/autobahn.min.js";
    script.charset="utf-8";
    document.body.appendChild(script);

The result is the same as in my initial comment. It works on Amazon, but not on BackCountry. Here is a screenshot of what happens when I execute the above on http://www.backcountry.com:

![](http://imageshack.com/a/img538/9319/yzA7Cj.png)

The line number in the screenshot is different than in my initial comment because I stuck the un-minified code in the JS file. This is the line the error is being thrown on:

    ab._UA_FIREFOX = new RegExp(".*Firefox/([0-9+]*).*")

Which looks like the first usage of `ab`. So it would seem that the `ab` object is not being created successfully for some reason.

Any idea what the problem might be?

Thanks so much for your time,

Nate

**Comment by oberstet** [comment]
The `ab` object was actually the entry point of the "old" AutobahnJS (WAMP1) - which is deprecated and incompatible with the new one (WAMP2): http://autobahn.ws/js/gettingstarted.html#browsers

I haven't used that for ages, but I would try to get rid of the fancy method of dynamically inserting a script tag, and add a plain script tag with src into the HTML either in head or body.
