### ISSUE TITLE
Support for salted passwords

### ISSUE THREAD

**Issue by jennolsen84** [tavendo/AutobahnJS#124]
Seems like after 0.9 (WAMP2), the supported for salted passwords was deprecated.  Would be very nice to have them back :)

**Comment by oberstet** [comment]
It's there already https://github.com/crossbario/crossbarexamples/blob/master/authenticate/wampcra/web/index.html#L20

**Comment by jennolsen84** [comment]
Yes, just found it (feel dumb).. was looking for the old function.  I came to close the bug -- you are too fast

**Comment by oberstet** [comment]
no problem - I love easy to close issues;)
