### ISSUE TITLE
AutobahnJS does not work in a web worker

### ISSUE THREAD

**Issue by Ramzeus** [tavendo/AutobahnJS#133]
The code for creating a WAMP transport works only in the main browser thread or on NodeJS but not in a web worker.

The code looks like this:
>   //
>   // running in browser
>   //
> if ('window' in global) {
> ...
>
>   //
>   // running on NodeJS
>   //
>   } else {
> ...
>}

When I try in a web worker it cannot initialize the WebSocket class because it gets wrong parameters and the open() call fails with an error that says: unsupported

**Comment by goeddea** [comment]
Yep, that didn't work.

Should be in the next release of Autobahn|JS.

To try out now build from trunk or use https://www.dropbox.com/s/ghi2vzsrr5l58e0/autobahn_2015-03-15.zip?dl=0 which is a build that integrates it.
