### ISSUE TITLE
"The connection to ws://.. was interrupted while the page was loading" error in FireFox

### ISSUE THREAD

**Issue by nhouse** [tavendo/AutobahnJS#136]
I'm using the latest versions of AutobahnJS and Thruway.

In FireFox I'm getting the following error in the console on page load:

> The connection to ws://dev.pricewombat.com:9090/ was interrupted while the page was loading.

I found these topics on the discussion:

http://stackoverflow.com/questions/4812686/closing-websocket-correctly-html5-javascript
http://stackoverflow.com/questions/14140414/websocket-interrupted-while-page-is-loading-on-firefox-for-socket-io

Based on the answers there, I tried adding this inside of `connection.onopen()`:

    $(window).on('beforeunload', function(){ 
        connection.close();
    });

I also tried the non-jQuery version:

    window.onbeforeunload = function() {
        connection.close();
    };

But the error is still there.

Related FireFox bug reports:

https://bugzilla.mozilla.org/show_bug.cgi?id=712329
https://bugzilla.mozilla.org/show_bug.cgi?id=765738

Is there any way to eliminate this error?

**Comment by oberstet** [comment]
can't reproduce (using Crossbar.io)
