### ISSUE TITLE
Multiple subscriptions -> only last will work

### ISSUE THREAD

**Issue by DominikVogt** [tavendo/AutobahnJS#137]
I am using WAMP v1 Autobahn, witch Ratchet Server application in laravel framework.

It seems that i can subscribe to single chat subscriptions, but once i try to do this for all chat rooms, only the last subscriptions stays alive/gives feedback. Even though when i check, i see all subscriptions.

PHP Server is sending response to subscriptions
```
$client->event('chat.updatejson.'.$chatRoom->id, $json_response);
```

Client is subscribing to each topic in an array of chats
```
$rootScope.SOCKET_SESSION.call("chat.update.auth", chat_id, $rootScope.clientID, $rootScope.socket_token).then(function (result) {
  $rootScope.SOCKET_SESSION.subscribe("chat.updatejson."+chat_id, function (topic, event) {
    console.log("chat.updatejson from index");
	var message = {
		id: event.data[0].id,
		chat_id: event.data[0].chat_id,
		text: event.data[0].text,
		created_at: event.data[0].created_at,
		author: event.data[0].author.data[0]
	}
	_addMessage(message);
  });
});
```

When i display the subscriptions in console i get 
```
_subscriptions: Object
chat.updatejson.5: Array[1]
chat.updatejson.24: Array[1]
chat.updatejson.25: Array[2]
chat.updatejson.26: Array[1]
chat.updatejson.27: Array[1]
```

When i now try to send messages to the server from a different client i only get messages from the last registered subscription. Can you give me a hind how to solve it?

**Comment by goeddea** [comment]
Sorry, but WAMP v1 is a deprecated version of the protocol. We do not have the time to look into issues with this anymore. Closing because of this.

Maybe somebody else can help you, though. My suggestion is to try on the Autobahn mailing list - https://groups.google.com/forum/#!forum/autobahnws
