### ISSUE TITLE
Typescript example & tutorial please !

### ISSUE THREAD

**Issue by bradws** [tavendo/AutobahnJS#145]
Hi team,

The readme contains a good example of using AutobahnJS on the server, but can anyone assist with using this with Typescript now that Definitely Typed v0.0.1 is out?

For example, the typescript compiler (v1.5.0-beta) gets an error: "Cannot find external module 'autobahn.js'" on the first line "import autobahn = require('autobahn');"
..and im compiling with:
"tsc example02.ts --module commonjs --target es5"

I've installed AutobahnJS with >npm install autobahn in the project folder. 
I've even tried "import autobahn = require('C:/DEV/SRC/RESEARCH/WEBAPPS/TYPESCRIPT/example02/node_modules/autobahn/lib/autobahn.js');" and it still doesn't seem to find it.

Thanks,
Brad

**Comment by goeddea** [comment]
I've never used TypeScript, and the same goes for the others on the project, so I have no idea what the problem there is. 

We're tool-agnostic, so we would like to offer support for TypeScript (whatever gets the job done for people is what they should use), but it's not on our list of priorities to do so ourselves.

Could you post your request on the mailing list (https://groups.google.com/forum/#!forum/autobahnws) - chances that somebody can help you out are bigger there.

Closing this: It's a valid request, but realistically not something we're going to have the resources to address.

BTW - Should you be able to solve the problem,  then a quick note on this would be welcome. While we don't have the resources to look into this ourselves, I'd certainly add a solution to the documentation.

**Comment by darkl** [comment]
Hi @bradws,
I think your issue should be solved now thanks to [this pull request](https://github.com/borisyankov/DefinitelyTyped/pull/5115).

You can find a very simple demo (based on the README sample) [here](https://github.com/borisyankov/DefinitelyTyped/blob/master/autobahn/autobahn-tests.ts).

Hope it helps,
Elad
