### ISSUE TITLE
AutobahnJS does not work on windows 10 

### ISSUE THREAD

**Issue by craigbroadbear** [tavendo/AutobahnJS#149]
I am using crossbar.io 0.10.4 broker and node.js 0.12.0 / autobahn 0.9.6 clients & servers.  
Everything works well initially but after a while (e.g. 10 mins), all RPC fails.
e.g. error:
{
  "error": "wamp.error.no_such_procedure",
  "args": [
    "no callee registered for procedure 'session.get'"
  ],
  "kwargs": {}
}
The  crossbar server appears to be running fine, the RPC services show no indication of error.
If I restart my RPC services all goes well. 
I am developing on Windows 10.

I am starting to suspect autobahn on Windows 10.  My code runs fine on Win 2008 R2.

**Comment by craigbroadbear** [comment]
Seems to be a autobahn on Windows 10 problem.  Code runs fine with same versions of everything on Win 2008R2 and Windows 7.

**Comment by oberstet** [comment]
what's your exact setup?

- You have 2 WAMP components, both written in JS running on Node on Windows 10 using AutobahnJS? So we are NOT talking about MS Edge _browser_, right?
- Those 2 WAMP components and the Crossbar.io router .. on what machines do they run? Three different boxes? On the same LAN?

In general, when things "don't work after some time", that might be related to a network intermediary (or something else) timing out an idle TCP connection. Crossbar.io has WebSocket auto ping/pong built in. You could try to activate that: http://crossbar.io/docs/WebSocket-Options/#production-settings => the "auto*" options ..

**Comment by craigbroadbear** [comment]
I have been running with those exact settings on crossbar for some days
now.  Problem still occurs.

Crossbar.io server - It does not appear to matter where this runs.  I have
tried this on Win 10 and Win200R2.

Setup:
test_server.js - a simple RPC server.
test_client.js - a simple RPC client.
node version : 0.12.7
autobahnjs : 0.9.6
crossbar : 0.10.4

To reproduce issue, run the test_server on win 10 machine.  Then run the
test_client - it works.  Kill test client and re-run it "some time" latter.

e.g. more than 5 minutes, less than an hour.  It spits out the "no callee
registered for procedure" error.

The above test works fine on Win2008R2 and Win7.  Not so Win10  (but I have
only tried one win10 machine so far)

test_server.js:
var autobahn = require('autobahn');
var config = require('../app/config/default.json')
var connection = new autobahn.Connection(config.client.autobahn);

connection.onopen = function (session)
{
console.log("onopen");
session.register('rpc.test', rpcTest);
}
connection.onclose = function(parms)
{
console.log("onclose "+parms);
}
connection.open();

function rpcTest(args)
{
console.log("rpcTest - "+ JSON.stringify(args));
return "done";
}
test_client.js
var autobahn = require('autobahn');
var config = require('../app/config/default.json');

var connection = new autobahn.Connection(config.client.autobahn);

connection.onopen = function (session)
{
session.call('rpc.test', ["test parm"]).then(
function (res)
{
console.log("success:" + JSON.stringify(res, null, 2))
},
function (res)
{
console.log("error: " + JSON.stringify(res, null, 2))
}
);
}
connection.open();


Broadgun Software
www.pdfmachine.com

**Comment by craigbroadbear** [comment]
Can confirm issue occurs on another Windows 10 box, running an older version of node.  Seems to be a autobahnjs on Win10 issue.

**Comment by oberstet** [comment]
@craigbroadbear to bisect, could you run your component not under Node, but say Chrome on Windows 10? I have a hard time believing the source of the issue is AutobahnJS ...

**Comment by craigbroadbear** [comment]
So I adapted the above example code, client and server, to work in a browser.  It works under chrome & edge on Windows 10.  Is there some sort of debug mode i can enable to see what is going on?

**Comment by oberstet** [comment]
You can enable `AUTOBAHN_DEBUG`: https://github.com/tavendo/AutobahnJS/blob/master/package/lib/log.js#L17

FWIW, there are 2 major differences with AutobahnJS running in browser vs node:

1. (obviously) Node
2. WebSocket doesn't come from browser native implementation, but from `ws`: https://github.com/tavendo/AutobahnJS/blob/master/package/package.json#L11

**Comment by craigbroadbear** [comment]
Enabling the debug option did not highlight any issues.

I changed the connection string to use "localhost" now everything is working.  Seems like some bug in the ws implementation not handling my networking setup with win 10.

**Comment by oberstet** [comment]
@craigbroadbear good to hear you got it solved. if you haven't done already, pls consider informing the ws https://github.com/websockets/ws - others will likely run into this also.

**Comment by craigbroadbear** [comment]
Will do. Thanks for your help!
Cheers,
Craig
