### ISSUE TITLE
How to catch errors?

### ISSUE THREAD

**Issue by nhouse** [tavendo/AutobahnJS#158]
Hi, this is a really basic question, but how do I go about catching Autobahn JS errors?

As an example, I'm getting the following output in my console:

    autobahn.1429491778.min.js:formatted:2457 WebSocket connection to 'ws://dev.pricewombat.com:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

I tried putting my connection code inside of a try/catch block, but the above error is still logged in the console and my code in the `catch` block is never executed.

    try {
        if (typeof autobahn !== "undefined") {
            var connection = new autobahn.Connection({
                                                         url: priceWombat.localhost ? 'ws://dev.pricewombat.com:9090' : 'wss://www.pricewombat.com:9090',
                                                         realm: 'restricted_realm'
                                                     });
    
            connection.onopen = function (session) {
                priceWombat.webSocketOpened = true;
                priceWombat.webSocket = session;
    
                $(window).on('beforeunload', function () {
                    connection.close();
                });
    
                window.onbeforeunload = function () {
                    connection.close();
                };
            };
    
            connection.open();
        }
    } catch (e) {
        console.log('error caught: ' + e);
    }

**Comment by oberstet** [comment]
we have a mailing list for questions https://groups.google.com/forum/#!forum/autobahnws
