### ISSUE TITLE
Missing doc for default Defer(red)

### ISSUE THREAD

**Issue by Paranaix** [tavendo/AutobahnJS#159]
While the API Reference states that one can replace the used factory for deferreds (and by doing so the returned objects), It fails to mention:

1. What factory/class is used as default
2. What interface yonder class provides

**Comment by oberstet** [comment]
"Options that control what kind of Deferreds to use:" here http://autobahn.ws/js/reference.html#connection-options

**Comment by Paranaix** [comment]
I think you missunderstood me: My issue with the documentation is, that it doesn't state what Deferred it uses if nothing is specified (the default one) and what interface yonder Deferreds provide.

**Comment by goeddea** [comment]
@Paranaix - added pointers to when.js both in the "Introduction to WAMP Programming" and the "API Reference".
